### ISSUE TITLE
Implement filter by status in API

### ISSUE THREAD

**Issue by stev0531** [UMM-CSci-3601-F17/lab-4-angular-spark-and-mongodb-liz-colin#9]

**Comment by rabex028** [comment]
It seems that because status is defined as a boolean, there is different behavior for the database regex queries for this property. Since status will probably be a dropdown on the client side, it may not be necessary to use a regex query for status anyway though. The alternative would probable be to make status a string on the backend (like it will probably be on the front end). For now I am just going to leave out the regex query part of the filter until we decide later.
